SpareGear1/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from gears.views import home

#from userena import views as userena_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gears/', include('gears.urls', namespace="gears")),
    url(r'^$' ,home , name='home'),
]

gears/urls.py
from django.conf.urls import url
from. import views

urlpatterns = [

    url(r'^$' , views.home , name='home'),
    url(r'^show/', views.show_gear , name='show'),
    url(r'^add_gear/', views.add_gear , name='add_gear'),

]

gears/models.py
from __future__ import unicode_literals

from django.db import models



type_choices=(
    ('','--'),
    ('car','car gears'),
    ('home','home gears'),
    ('electroics', 'electronic gears'),
    ('computers', 'computer gears'),
    ('office', 'office equipment gears'),
    ('medical', 'medical equipment gears'),
)

quality_choices=(
    ('','--'),
    ('E','excellent'),
    ('G','good'),
    ('B','bad'),
)
class Gear (models.Model):
    gear_type = models.CharField (max_length=100, choices=type_choices)
    gear_producer = models.CharField (max_length=100)
    gear_name = models.CharField (max_length=100)
    gear_model = models.CharField (max_length=100)
    gear_date = models.CharField (max_length=100)
    gear_quality = models.CharField (max_length=100, choices=quality_choices)
    gear_availablity = models.BooleanField(max_length=100)
    gear_owner = models.CharField (max_length=100)
    gear_price = models.CharField (max_length=100)
    gear_image = models.FileField(null=True, blank=True)

gears/forms.py
from django import forms
from gears.models import Gear

class add_gearForm(forms.ModelForm):
    class Meta:
        model =Gear
        fields = ['gear_type','gear_producer','gear_name','gear_model','gear_quality','gear_availablity','gear_price']

gears/views.py
# -*- coding: utf-8 -*-
#from future import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from gears.forms import add_gearForm
from gears.models  import Gear
# Create your views here.

def home(request):
    return render(request, "home.html")#response

#def index(request):
   # return HttpResponse('SpareGear')

def show_gear(request):
    return render (request, "show.html")#response

def add_gear(request):


    if request.method == 'POST':
        Form = add_gearForm(request.POST)
        if Form.is_valid():
            Form.save()
            return HttpResponseRedirect(reverse('gears:show'))

    elif request.method == 'GET':

        form = add_gearForm()

    return render(request, "add_gear.html", {'form': form})

gears/templates/add_gear.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% block content%}



<form class="form" enctype="multipart/form-data"  action="{% url 'gears:add_gear' %}" method="post">

    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
        <button type="submit" class="btn btn-primary">
             أرسل
        </button>
        {% endbuttons %}

</form>
{% endblock %}

</body>
</html>

gears/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NOURA</title>
</head>
<body>
noura
</body>
</html>

gears/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>